//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aseguradora_web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURO
    {
        public int ID { get; set; }
        public int ID_TIPO_SEGURO { get; set; }
        public string NOMBRE { get; set; }
        public string POLIZA_DESCRIPCION { get; set; }
        public double VALOR_UF { get; set; }
    }
}
